use crate::audio::types::RecordingState;
use crate::state::SharedState;
use crate::{do_pause_recording, do_resume_recording, do_start_recording, do_stop_recording};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::time::Duration;
use tauri::{AppHandle, Emitter, Manager};
use tauri_plugin_global_shortcut::{GlobalShortcutExt, Shortcut, ShortcutEvent, ShortcutState};

/// Threshold: hold >= LONG_PRESS_MS triggers immediate stop.
const LONG_PRESS_MS: u64 = 500;

/// `true` while the physical key is held down (first press until release).
static PRESS_ACTIVE: AtomicBool = AtomicBool::new(false);

/// Set by the timer thread when it fires stop — prevents `Released` from
/// executing a short-press action on the same cycle.
static STOP_TRIGGERED: AtomicBool = AtomicBool::new(false);

/// Monotonic counter: each *first* press increments this so stale timers
/// (from a previous press/release cycle) can detect they are outdated.
static PRESS_EPOCH: AtomicU64 = AtomicU64::new(0);

/// Register the global hotkey. Safe to call multiple times (re-registration).
pub fn register(app: &AppHandle, shortcut_str: &str) -> Result<(), String> {
    let manager = app.global_shortcut();

    // Unregister all first (safe no-op if nothing registered)
    let _ = manager.unregister_all();

    let shortcut: Shortcut = shortcut_str
        .parse()
        .map_err(|e| format!("Invalid shortcut '{shortcut_str}': {e}"))?;

    let app_handle = app.clone();
    manager
        .on_shortcut(shortcut, move |_app, _shortcut, event| {
            handle_shortcut_event(&app_handle, event);
        })
        .map_err(|e| format!("Failed to register shortcut: {e}"))?;

    log::info!("Global hotkey registered: {shortcut_str}");
    Ok(())
}

fn handle_shortcut_event(app: &AppHandle, event: ShortcutEvent) {
    match event.state {
        ShortcutState::Pressed => {
            // Ignore key-repeat events generated by the OS while held.
            if PRESS_ACTIVE.load(Ordering::SeqCst) {
                return;
            }

            PRESS_ACTIVE.store(true, Ordering::SeqCst);
            STOP_TRIGGERED.store(false, Ordering::SeqCst);
            let epoch = PRESS_EPOCH.fetch_add(1, Ordering::SeqCst) + 1;

            // Only spawn the stop-timer when a recording is active.
            let state = match app.try_state::<SharedState>() {
                Some(s) => s,
                None => return,
            };
            let current = match state.lock() {
                Ok(s) => s.recording_state.clone(),
                Err(_) => return,
            };

            if matches!(current, RecordingState::Recording | RecordingState::Paused) {
                let app_clone = app.clone();
                std::thread::Builder::new()
                    .name("hotkey-timer".into())
                    .spawn(move || {
                        std::thread::sleep(Duration::from_millis(LONG_PRESS_MS));

                        // Only fire if the key is still held AND this is the
                        // same press cycle that spawned us.
                        if PRESS_ACTIVE.load(Ordering::SeqCst)
                            && PRESS_EPOCH.load(Ordering::SeqCst) == epoch
                        {
                            STOP_TRIGGERED.store(true, Ordering::SeqCst);
                            if let Err(e) = do_stop_recording(&app_clone) {
                                log::error!("Hotkey timer stop failed: {e}");
                            }
                        }
                    })
                    .ok();
            }
        }
        ShortcutState::Released => {
            PRESS_ACTIVE.store(false, Ordering::SeqCst);

            // Timer already executed stop — nothing to do.
            if STOP_TRIGGERED.load(Ordering::SeqCst) {
                return;
            }

            // Short press — standard toggle logic.
            let state = match app.try_state::<SharedState>() {
                Some(s) => s,
                None => return,
            };
            let current = match state.lock() {
                Ok(s) => s.recording_state.clone(),
                Err(_) => return,
            };

            match current {
                RecordingState::Idle => {
                    if let Err(e) = do_start_recording(app) {
                        log::error!("Hotkey start failed: {e}");
                        let _ = app.emit("recording-error", e);
                    }
                }
                RecordingState::Recording => {
                    if let Err(e) = do_pause_recording(app) {
                        log::error!("Hotkey pause failed: {e}");
                    }
                }
                RecordingState::Paused => {
                    if let Err(e) = do_resume_recording(app) {
                        log::error!("Hotkey resume failed: {e}");
                    }
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    /// Serializes tests that mutate shared global atomics.
    static TEST_LOCK: Mutex<()> = Mutex::new(());

    fn reset() {
        PRESS_ACTIVE.store(false, Ordering::SeqCst);
        STOP_TRIGGERED.store(false, Ordering::SeqCst);
        PRESS_EPOCH.store(0, Ordering::SeqCst);
    }

    #[test]
    fn press_active_ignores_repeat() {
        let _g = TEST_LOCK.lock().unwrap();
        reset();

        // First press sets the flag
        PRESS_ACTIVE.store(true, Ordering::SeqCst);
        PRESS_EPOCH.fetch_add(1, Ordering::SeqCst);

        // Repeat press should be ignored because PRESS_ACTIVE is true
        assert!(PRESS_ACTIVE.load(Ordering::SeqCst));
    }

    #[test]
    fn release_resets_press_active() {
        let _g = TEST_LOCK.lock().unwrap();
        reset();

        PRESS_ACTIVE.store(true, Ordering::SeqCst);
        // Simulate release
        PRESS_ACTIVE.store(false, Ordering::SeqCst);
        assert!(!PRESS_ACTIVE.load(Ordering::SeqCst));
    }

    #[test]
    fn stop_triggered_blocks_release_action() {
        let _g = TEST_LOCK.lock().unwrap();
        reset();

        // Timer fires stop while held
        STOP_TRIGGERED.store(true, Ordering::SeqCst);
        PRESS_ACTIVE.store(false, Ordering::SeqCst);

        // Released handler must bail early
        assert!(STOP_TRIGGERED.load(Ordering::SeqCst));
    }

    #[test]
    fn epoch_prevents_stale_timer() {
        let _g = TEST_LOCK.lock().unwrap();
        reset();

        // Press 1 → epoch 1
        let epoch1 = PRESS_EPOCH.fetch_add(1, Ordering::SeqCst) + 1;
        // Release + Press 2 → epoch 2
        let epoch2 = PRESS_EPOCH.fetch_add(1, Ordering::SeqCst) + 1;

        // Stale timer (epoch1) checks current epoch — must not match
        assert_ne!(epoch1, PRESS_EPOCH.load(Ordering::SeqCst));
        assert_eq!(epoch2, PRESS_EPOCH.load(Ordering::SeqCst));
    }

    #[test]
    fn long_press_constant_is_500ms() {
        assert_eq!(LONG_PRESS_MS, 500);
    }

    #[test]
    fn fresh_state_is_inactive() {
        let _g = TEST_LOCK.lock().unwrap();
        reset();

        assert!(!PRESS_ACTIVE.load(Ordering::SeqCst));
        assert!(!STOP_TRIGGERED.load(Ordering::SeqCst));
        assert_eq!(PRESS_EPOCH.load(Ordering::SeqCst), 0);
    }
}
